[project]
authors = ["Chaebeom Sheen <cauchybs@snu.ac.kr>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "aisafe_back"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch = ">=2.4.0,<3"
jax = ">=0.4.31,<0.5"
numpy = ">=2.1.1,<3"
scipy = ">=1.14.1,<2"
uv = ">=0.4.4,<0.5"
mypy = ">=1.11.2,<2"
ruff = ">=0.6.2,<0.7"
pre-commit = ">=3.8.0,<4"
pytest = ">=8.3.2,<9"
hypothesis = ">=6.111.2,<7"
cookiecutter = ">=2.6.0,<3"
tqdm = ">=4.66.5,<5"
scikit-learn = ">=1.5.2,<2"
jupyter = ">=1.1.1,<2"
pip = ">=24.2,<25"
python = ">=3.12.6,<4"
nvtop = ">=3.1.0,<4"

[pypi-dependencies]
build = ">=1.2.2, <2"
setuptools = "*"
