[project]
authors = ["Chaebeom Sheen <cauchybs@snu.ac.kr>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "aisafe_back"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch = ">=2.4.0,<3"
jax = ">=0.4.31,<0.5"
numpy = ">=2.1.1,<3"
scipy = ">=1.14.1,<2"
uv = ">=0.4.4,<0.5"
mypy = ">=1.11.2,<2"
ruff = ">=0.6.2,<0.7"
pre-commit = ">=3.8.0,<4"
pytest = ">=8.3.2,<9"
hypothesis = ">=6.111.2,<7"
cookiecutter = ">=2.6.0,<3"
jupyter = ">=1.1.1,<2"
dlib = ">=19.24.6,<20"
imutils = ">=0.5.4,<0.6"
keras = ">=3.5.0,<4"
scikit-learn = ">=1.5.2,<2"
torchvision = ">=0.19.0,<0.20"
pillow = ">=10.4.0,<11"
pydub = ">=0.25.1,<0.26"
transformers = ">=4.41.2,<5"
pandas = ">=2.2.2,<3"
moviepy = ">=1.0.3,<2"
nvtop = ">=3.1.0,<4"

[pypi-dependencies]
torchaudio = ">=2.4.0, <3"
opencv-python = "*"
pyaudioanalysis = ">=0.2.5, <0.3"
